model:
  type: resnet18
dataset: cifar10
batch: 128
epoch: 300
writer: False
lr: 0.1
lr_schedule:
  type: 'cosine'
  warmup: 
    multiplier: 1
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005
  ema: 0
